server:
  port: 9090

spring:
  cloud:
    gateway:
      mvc:
        routesMap:
          item-server:
            uri: http://localhost:8081
            predicates:
              - Path=/item-api/**
          order-server:
            uri: http://localhost:8082
            predicates:
              - Path=/order-api/**
          user-server:
            uri: http://localhost:8083
            predicates:
              - Path=/user-api/**
