server:
  port: 9090

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: item-server
            uri: http://localhost:8081
            predicates:
              - Path=/item-api/**
